orion:
  image: fiware/orion
  links:
    - mongo
    - cygnus
    - accumulator
  ports:
    - "1026:1026"
  command: -dbhost mongo
accumulator:
  build: accumulator
  ports:
    - "1028:1028"
  command: ./accumulator-server.py
mongo:
  image: mongo:3.2
  command: --smallfiles --nojournal
  ports:
    - "27018:27017" # port opened only for development environment
cygnus:
  build: fiware-cygnus/docker/cygnus-ngsi
  ports:
    - "8081:8081"
    - "5050:5050"
